pipeline {
    agent {
        label 'ec2'
    }
    stages {
        stage('Pull'){
            steps{
                slackSend(color: "#FFFE89", channel: "ensure-deployments" , message: "...Starting Ensure Proxy DEV Deployment...") 	   
              script{  
                dir ('drupal_src'){              
                    git credentialsId: "github_globant", branch:"master",url:"https://github.globant.com/Abbott/Ensure-Drupal.git"
                }
              }
            }
        }
        stage('login ECR'){
            steps{
                script{
                    sh 'aws ecr get-login-password --region us-west-2 | docker login --username AWS --password-stdin 271592211585.dkr.ecr.us-west-2.amazonaws.com'
                }
            }
        }
        stage('Build Docker Image') {
            steps{
                 script {
                    sh 'docker -v'
                    sh 'sudo chmod 666 /var/run/docker.sock'
                    sh 'docker build --no-cache -t 271592211585.dkr.ecr.us-west-2.amazonaws.com/ensure_registry:proxy_${BUILD_NUMBER} -f /home/ubuntu/workspace/Ensure/Dev/proxy/Dockerfile .'
                    sh 'docker image ls -a'
                }

            }
        }    
        stage('Publish Image'){
            steps{
                script{
                    sh 'docker tag 271592211585.dkr.ecr.us-west-2.amazonaws.com/ensure_registry:proxy_${BUILD_NUMBER} 271592211585.dkr.ecr.us-west-2.amazonaws.com/ensure_registry:proxy_ensure'
                    sh 'docker push 271592211585.dkr.ecr.us-west-2.amazonaws.com/ensure_registry:proxy_ensure '
                }
            }
        }
        
        stage('Deploy DEV'){
            steps{
                script{
                    sh 'aws ecs update-service --force-new-deployment --service ensure-dev-httpd-ecs-service --cluster ensure-dev-cluster'
                }
            }
        }
    }
    post {
      success {
        slackSend(color: "#00FF00", channel: "ensure-deployments" , message: "...Successful Proxy DEV Deployment...")
        slackSend(color: "#D4DADF", channel: "ensure-deployments" , message: "Please check your Proxy DEV changes in 3 minutes..")
      }
      failure {
        slackSend(color: "#FF9FA1", channel: "ensure-deployments" , message: "...Failed Proxy Dev Deployment...")
      }
    }
}
